import { mutation } from "./_generated/server";

// All 59 Cuyahoga County municipalities + County + State
const MUNICIPALITY_CODE_MATRIX = [
  // ===== OHIO STATE (Baseline) =====
  {
    municipality: "OHIO STATE",
    municipalityType: "state" as const,
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    energyCode: "IECC 2021",
    localAmendmentsNotes: "State baseline codes - municipalities may adopt stricter requirements",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    roofPermitNotes: "Required for structural changes, re-roofing over existing layers",
    deckPermitRequired: true,
    deckPermitThreshold: "Over 200 sq ft or 30 inches above grade",
    fencePermitRequired: false,
    fenceHeightLimit: "No state limit - check local",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    aduNotes: "Ohio allows ADUs subject to local zoning",
    strAllowed: true,
    strNotes: "No state restrictions - check local",
    smokeDetectorRequirements: "Required in each bedroom, outside sleeping areas, each level including basement",
    coDetectorRequirements: "Required on each level with sleeping areas if fuel-burning appliances or attached garage",
  },

  // ===== CUYAHOGA COUNTY (Unincorporated) =====
  {
    municipality: "CUYAHOGA COUNTY",
    municipalityType: "county" as const,
    buildingDeptPhone: "216-443-7850",
    buildingDeptWebsite: "https://cuyahogacounty.us/development",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    roofPermitFee: "$75-150",
    deckPermitRequired: true,
    deckPermitThreshold: "Over 200 sq ft",
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per Ohio State code",
    coDetectorRequirements: "Per Ohio State code",
  },

  // ===== CITIES (Alphabetical) =====

  {
    municipality: "BAY VILLAGE",
    municipalityType: "city" as const,
    population: 15000,
    buildingDeptPhone: "440-871-2200",
    buildingDeptWebsite: "https://www.cityofbayvillage.com/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleNotes: "Required for all residential sales. Exterior and safety inspection.",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    occupancyPermitFee: "$50",
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    deckPermitFee: "$75",
    deckPermitThreshold: "Any attached deck",
    fencePermitRequired: true,
    fencePermitFee: "$25",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacPermitFee: "$75",
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalPermitFee: "$75",
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingPermitFee: "$75",
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    demolitionPermitFee: "$100",
    aduAllowed: false,
    aduNotes: "Not currently permitted in single-family zones",
    strAllowed: false,
    strNotes: "Short-term rentals prohibited",
    smokeDetectorRequirements: "Hardwired with battery backup required at POS",
    coDetectorRequirements: "Required on each level",
  },

  {
    municipality: "BEACHWOOD",
    municipalityType: "city" as const,
    population: 13000,
    buildingDeptPhone: "216-464-1070",
    buildingDeptWebsite: "https://www.beachwoodohio.com/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021 + Local",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$150",
    pointOfSaleNotes: "Comprehensive interior/exterior inspection required",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$100/year",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Every 2 years",
    occupancyPermitRequired: true,
    occupancyPermitFee: "$75",
    roofPermitRequired: true,
    roofPermitFee: "$100",
    deckPermitRequired: true,
    deckPermitFee: "$100",
    fencePermitRequired: true,
    fencePermitFee: "$50",
    fenceHeightLimit: "6ft max",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    smokeDetectorRequirements: "Hardwired interconnected in all bedrooms and hallways",
    coDetectorRequirements: "Required each level",
  },

  {
    municipality: "BEDFORD",
    municipalityType: "city" as const,
    population: 12500,
    buildingDeptPhone: "440-232-1600",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleNotes: "Pre-sale inspection covering safety items",
    pointOfSaleValidDays: 120,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$75/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    strPermitRequired: true,
    smokeDetectorRequirements: "All bedrooms and hallways",
    coDetectorRequirements: "Each level with fuel appliances",
  },

  {
    municipality: "BEDFORD HEIGHTS",
    municipalityType: "city" as const,
    population: 10200,
    buildingDeptPhone: "440-786-3200",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 120,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "BEREA",
    municipalityType: "city" as const,
    population: 18500,
    buildingDeptPhone: "440-826-5800",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$35/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$60",
    deckPermitRequired: true,
    deckPermitFee: "$60",
    fencePermitRequired: true,
    fencePermitFee: "$25",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "BRATENAHL",
    municipalityType: "village" as const,
    population: 1400,
    buildingDeptPhone: "216-681-4266",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    historicDistricts: true,
    historicDistrictNotes: "Architectural review required for exterior changes",
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "BRECKSVILLE",
    municipalityType: "city" as const,
    population: 13600,
    buildingDeptPhone: "440-526-4351",
    buildingDeptWebsite: "https://www.brecksville.oh.us/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    localAmendmentsNotes: "Strict exterior maintenance standards, architectural review for new construction",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$150",
    pointOfSaleNotes: "Comprehensive inspection required. Very thorough.",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$75/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Annual",
    occupancyPermitRequired: true,
    occupancyPermitFee: "$50",
    roofPermitRequired: true,
    roofPermitFee: "$100",
    deckPermitRequired: true,
    deckPermitFee: "$100",
    deckPermitThreshold: "Any deck requires permit",
    fencePermitRequired: true,
    fencePermitFee: "$50",
    fenceHeightLimit: "6ft rear, 4ft front, architectural standards apply",
    hvacPermitRequired: true,
    hvacPermitFee: "$75",
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalPermitFee: "$75",
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingPermitFee: "$75",
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    demolitionPermitFee: "$200",
    aduAllowed: false,
    aduNotes: "Not permitted - strict single-family zoning",
    strAllowed: false,
    strNotes: "Short-term rentals prohibited",
    smokeDetectorRequirements: "Hardwired interconnected, battery backup, all bedrooms + hallways",
    coDetectorRequirements: "Required each level, hardwired preferred",
  },

  {
    municipality: "BROADVIEW HEIGHTS",
    municipalityType: "city" as const,
    population: 19400,
    buildingDeptPhone: "440-717-4014",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$85",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    strPermitRequired: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "BROOK PARK",
    municipalityType: "city" as const,
    population: 18500,
    buildingDeptPhone: "216-433-1502",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 120,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$65",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "BROOKLYN",
    municipalityType: "city" as const,
    population: 10600,
    buildingDeptPhone: "216-635-4207",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$75",
    pointOfSaleValidDays: 90,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$40/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "BROOKLYN HEIGHTS",
    municipalityType: "village" as const,
    population: 1500,
    buildingDeptPhone: "216-749-7107",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "CHAGRIN FALLS",
    municipalityType: "village" as const,
    population: 3900,
    buildingDeptPhone: "440-247-5050",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021 + Local",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$200",
    pointOfSaleNotes: "Strict inspection, historic district considerations",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$100/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$100",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "4ft front, 6ft rear - architectural review required",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    historicDistricts: true,
    historicDistrictNotes: "Downtown historic district - architectural board approval required",
    smokeDetectorRequirements: "Hardwired with battery backup",
    coDetectorRequirements: "Required each level",
  },

  {
    municipality: "CLEVELAND",
    municipalityType: "city" as const,
    population: 373000,
    buildingDeptPhone: "216-664-2282",
    buildingDeptWebsite: "https://www.clevelandohio.gov/building",
    buildingDeptAddress: "601 Lakeside Ave, Cleveland, OH 44114",
    buildingCode: "OBC 2024 + Local",
    residentialCode: "ORC 2024 + Local",
    electricalCode: "NEC 2023 + Local",
    plumbingCode: "OPC 2024 + Local",
    mechanicalCode: "OMC 2024 + Local",
    fireCode: "OFC 2024 + Local",
    propertyMaintenanceCode: "Cleveland Housing Code",
    energyCode: "IECC 2021",
    localAmendmentsNotes: "Cleveland has extensive local amendments. Lead-safe certification required for pre-1978 rentals.",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$175",
    pointOfSaleNotes: "Exterior point of sale. Interior inspection for 1-2 family. Valid 1 year. Repair escrow may be required.",
    pointOfSaleValidDays: 365,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$35/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Every 2 years",
    rentalRegistrationNotes: "Lead-safe certification required for pre-1978 buildings",
    occupancyPermitRequired: true,
    occupancyPermitFee: "$50",
    roofPermitRequired: true,
    roofPermitFee: "$75-200 based on value",
    roofPermitNotes: "Required for complete re-roof",
    deckPermitRequired: true,
    deckPermitFee: "$75-150",
    deckPermitThreshold: "Over 200 sq ft or 30 inches above grade",
    fencePermitRequired: true,
    fencePermitFee: "$35",
    fenceHeightLimit: "6ft rear, 4ft front, no barbed wire residential",
    hvacPermitRequired: true,
    hvacPermitFee: "$75-150",
    hvacLicensedContractorRequired: true,
    hvacPermitNotes: "HVAC contractor must be registered with city",
    electricalPermitRequired: true,
    electricalPermitFee: "$50-200",
    electricalLicensedContractorRequired: true,
    electricalPermitNotes: "Cleveland licensed electrician required",
    plumbingPermitRequired: true,
    plumbingPermitFee: "$50-200",
    plumbingLicensedContractorRequired: true,
    plumbingPermitNotes: "Cleveland licensed plumber required",
    demolitionPermitRequired: true,
    demolitionPermitFee: "$200-500",
    demolitionPermitNotes: "Asbestos survey required, utility disconnection verification",
    aduAllowed: true,
    aduNotes: "Allowed in certain zones with conditional use permit",
    strAllowed: true,
    strPermitRequired: true,
    strNotes: "Registration required, 2.5% bed tax applies",
    historicDistricts: true,
    historicDistrictNotes: "Multiple districts: Ohio City, Tremont, Detroit Shoreway - Landmark Commission approval required",
    smokeDetectorRequirements: "Hardwired with battery backup required. Each bedroom, outside sleeping areas, each level including basement.",
    coDetectorRequirements: "Required on each level with sleeping areas. Hardwired with battery backup.",
  },

  {
    municipality: "CLEVELAND HEIGHTS",
    municipalityType: "city" as const,
    population: 44000,
    buildingDeptPhone: "216-291-4878",
    buildingDeptWebsite: "https://www.clevelandheights.gov/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local Housing Code",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$150",
    pointOfSaleNotes: "Comprehensive inspection. Repair escrow possible. Very thorough.",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$75/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Every 3 years",
    occupancyPermitRequired: true,
    occupancyPermitFee: "$75",
    roofPermitRequired: true,
    roofPermitFee: "$100",
    deckPermitRequired: true,
    deckPermitFee: "$100",
    fencePermitRequired: true,
    fencePermitFee: "$50",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    aduNotes: "Recently allowed with restrictions",
    strAllowed: true,
    strPermitRequired: true,
    strNotes: "Permit and registration required",
    historicDistricts: true,
    historicDistrictNotes: "Several local historic districts - review required",
    smokeDetectorRequirements: "Hardwired interconnected, all bedrooms and hallways",
    coDetectorRequirements: "Required each level",
  },

  {
    municipality: "CUYAHOGA HEIGHTS",
    municipalityType: "village" as const,
    population: 600,
    buildingDeptPhone: "216-641-7020",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "EAST CLEVELAND",
    municipalityType: "city" as const,
    population: 13900,
    buildingDeptPhone: "216-681-2354",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 90,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$50",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "EUCLID",
    municipalityType: "city" as const,
    population: 47000,
    buildingDeptPhone: "216-289-2771",
    buildingDeptWebsite: "https://www.cityofeuclid.com/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021 + Local",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleNotes: "Required for 1-4 unit residential sales",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Every 2 years",
    occupancyPermitRequired: true,
    occupancyPermitFee: "$50",
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    deckPermitFee: "$75",
    fencePermitRequired: true,
    fencePermitFee: "$35",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    strPermitRequired: true,
    smokeDetectorRequirements: "Hardwired with battery backup",
    coDetectorRequirements: "Required each level",
  },

  {
    municipality: "FAIRVIEW PARK",
    municipalityType: "city" as const,
    population: 16000,
    buildingDeptPhone: "440-356-4440",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$40/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "GARFIELD HEIGHTS",
    municipalityType: "city" as const,
    population: 27000,
    buildingDeptPhone: "216-475-1100",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 120,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$65",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "GATES MILLS",
    municipalityType: "village" as const,
    population: 2200,
    buildingDeptPhone: "440-423-4405",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    fencePermitNotes: "Architectural review required",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    historicDistricts: true,
    historicDistrictNotes: "Village-wide architectural standards",
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "GLENWILLOW",
    municipalityType: "village" as const,
    population: 900,
    buildingDeptPhone: "440-439-1262",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "HIGHLAND HEIGHTS",
    municipalityType: "city" as const,
    population: 8100,
    buildingDeptPhone: "440-461-2440",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$75/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$85",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "HIGHLAND HILLS",
    municipalityType: "village" as const,
    population: 1100,
    buildingDeptPhone: "216-283-3000",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "HUNTING VALLEY",
    municipalityType: "village" as const,
    population: 700,
    buildingDeptPhone: "440-423-3246",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    fencePermitNotes: "Strict architectural standards",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    historicDistricts: true,
    historicDistrictNotes: "Village-wide standards, minimum lot sizes",
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "INDEPENDENCE",
    municipalityType: "city" as const,
    population: 7100,
    buildingDeptPhone: "216-524-1374",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$100",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "LAKEWOOD",
    municipalityType: "city" as const,
    population: 50000,
    buildingDeptPhone: "216-529-6270",
    buildingDeptWebsite: "https://www.lakewoodoh.gov/building",
    buildingCode: "OBC 2024 + Local",
    residentialCode: "ORC 2024 + Local",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local Housing Code",
    localAmendmentsNotes: "Lakewood has strict housing maintenance standards",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$150",
    pointOfSaleNotes: "Very thorough inspection. Common failures: smoke detectors, GFCI, handrails, window glazing.",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$60/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Every 3 years",
    occupancyPermitRequired: true,
    occupancyPermitFee: "$50",
    roofPermitRequired: true,
    roofPermitFee: "$85",
    roofPermitNotes: "Required for complete re-roof",
    deckPermitRequired: true,
    deckPermitFee: "$85",
    deckPermitThreshold: "Any attached deck",
    fencePermitRequired: true,
    fencePermitFee: "$35",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacPermitFee: "$75",
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalPermitFee: "$60",
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingPermitFee: "$60",
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    demolitionPermitFee: "$150",
    aduAllowed: true,
    aduNotes: "Recently allowed with lot size and parking requirements",
    strAllowed: true,
    strPermitRequired: true,
    strNotes: "Annual registration required, bed tax applies",
    historicDistricts: true,
    historicDistrictNotes: "Birdtown and downtown areas have review requirements",
    smokeDetectorRequirements: "Hardwired interconnected with battery backup in all bedrooms, hallways, each level",
    coDetectorRequirements: "Required on each level, hardwired preferred",
  },

  {
    municipality: "LINNDALE",
    municipalityType: "village" as const,
    population: 100,
    buildingDeptPhone: "216-398-0676",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "LYNDHURST",
    municipalityType: "city" as const,
    population: 13000,
    buildingDeptPhone: "440-442-5777",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$75/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$85",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "MAPLE HEIGHTS",
    municipalityType: "city" as const,
    population: 22000,
    buildingDeptPhone: "216-587-9032",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 120,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$60",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "MAYFIELD",
    municipalityType: "village" as const,
    population: 3400,
    buildingDeptPhone: "440-461-2210",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "MAYFIELD HEIGHTS",
    municipalityType: "city" as const,
    population: 18500,
    buildingDeptPhone: "440-442-2626",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$80",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "MIDDLEBURG HEIGHTS",
    municipalityType: "city" as const,
    population: 15500,
    buildingDeptPhone: "440-234-8811",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$40/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "MORELAND HILLS",
    municipalityType: "village" as const,
    population: 3300,
    buildingDeptPhone: "440-248-1188",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    fencePermitNotes: "Architectural review",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "NEWBURGH HEIGHTS",
    municipalityType: "village" as const,
    population: 1900,
    buildingDeptPhone: "216-641-4650",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "NORTH OLMSTED",
    municipalityType: "city" as const,
    population: 31000,
    buildingDeptPhone: "440-777-8000",
    buildingDeptWebsite: "https://www.north-olmsted.com/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$40/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    deckPermitFee: "$75",
    fencePermitRequired: true,
    fencePermitFee: "$30",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "NORTH RANDALL",
    municipalityType: "village" as const,
    population: 900,
    buildingDeptPhone: "216-662-6044",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "NORTH ROYALTON",
    municipalityType: "city" as const,
    population: 30700,
    buildingDeptPhone: "440-237-5380",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "OAKWOOD",
    municipalityType: "village" as const,
    population: 3600,
    buildingDeptPhone: "440-232-1313",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "OLMSTED FALLS",
    municipalityType: "city" as const,
    population: 8600,
    buildingDeptPhone: "440-235-3101",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$75",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$60",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "OLMSTED TWP",
    municipalityType: "township" as const,
    population: 13500,
    buildingDeptPhone: "440-235-3040",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "ORANGE",
    municipalityType: "village" as const,
    population: 3300,
    buildingDeptPhone: "440-498-4400",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$150",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "PARMA",
    municipalityType: "city" as const,
    population: 78000,
    buildingDeptPhone: "440-885-8088",
    buildingDeptWebsite: "https://www.cityofparma-oh.gov/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021 + Local",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleNotes: "Exterior and safety inspection required. Repair escrow possible.",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Every 2 years",
    occupancyPermitRequired: true,
    occupancyPermitFee: "$40",
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    deckPermitFee: "$75",
    deckPermitThreshold: "Over 200 sq ft",
    fencePermitRequired: true,
    fencePermitFee: "$30",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacPermitFee: "$65",
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalPermitFee: "$50",
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingPermitFee: "$50",
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    demolitionPermitFee: "$100",
    aduAllowed: false,
    strAllowed: true,
    strPermitRequired: true,
    smokeDetectorRequirements: "Per state code with local enforcement",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "PARMA HEIGHTS",
    municipalityType: "city" as const,
    population: 19500,
    buildingDeptPhone: "440-884-9607",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$45/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$65",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "PEPPER PIKE",
    municipalityType: "city" as const,
    population: 6200,
    buildingDeptPhone: "216-831-8500",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$200",
    pointOfSaleNotes: "Very comprehensive inspection",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$100",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fencePermitNotes: "Architectural approval required",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    historicDistricts: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "RICHMOND HEIGHTS",
    municipalityType: "city" as const,
    population: 10400,
    buildingDeptPhone: "216-486-2474",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$60/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "ROCKY RIVER",
    municipalityType: "city" as const,
    population: 20200,
    buildingDeptPhone: "440-331-0600",
    buildingDeptWebsite: "https://www.rfrr.us/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021 + Local",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$150",
    pointOfSaleNotes: "Thorough inspection, common failures: smoke detectors, GFCI",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$75/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Every 2 years",
    occupancyPermitRequired: true,
    occupancyPermitFee: "$50",
    roofPermitRequired: true,
    roofPermitFee: "$100",
    deckPermitRequired: true,
    deckPermitFee: "$100",
    fencePermitRequired: true,
    fencePermitFee: "$50",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    historicDistricts: true,
    historicDistrictNotes: "Downtown area has design review",
    smokeDetectorRequirements: "Hardwired with battery backup",
    coDetectorRequirements: "Required each level",
  },

  {
    municipality: "SEVEN HILLS",
    municipalityType: "city" as const,
    population: 11700,
    buildingDeptPhone: "216-524-4421",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "SHAKER HEIGHTS",
    municipalityType: "city" as const,
    population: 28000,
    buildingDeptPhone: "216-491-1400",
    buildingDeptWebsite: "https://www.shakeronline.com/building",
    buildingCode: "OBC 2024 + Local",
    residentialCode: "ORC 2024 + Local",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local Housing Code",
    localAmendmentsNotes: "Strict exterior maintenance and architectural standards",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$175",
    pointOfSaleNotes: "Very thorough. Historic district additional review.",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$100/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Annual",
    occupancyPermitRequired: true,
    occupancyPermitFee: "$75",
    roofPermitRequired: true,
    roofPermitFee: "$125",
    roofPermitNotes: "Architectural approval may be needed",
    deckPermitRequired: true,
    deckPermitFee: "$125",
    fencePermitRequired: true,
    fencePermitFee: "$75",
    fenceHeightLimit: "6ft rear, 4ft front, architectural standards",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    demolitionPermitFee: "$200",
    aduAllowed: true,
    aduNotes: "Recently approved with restrictions",
    strAllowed: false,
    strNotes: "Prohibited in residential zones",
    historicDistricts: true,
    historicDistrictNotes: "Extensive historic districts - Landmark Commission review required",
    smokeDetectorRequirements: "Hardwired interconnected with battery backup",
    coDetectorRequirements: "Required each level, hardwired",
  },

  {
    municipality: "SOLON",
    municipalityType: "city" as const,
    population: 23000,
    buildingDeptPhone: "440-248-1155",
    buildingDeptWebsite: "https://www.solonohio.org/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$150",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$75/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$100",
    deckPermitRequired: true,
    deckPermitFee: "$100",
    fencePermitRequired: true,
    fencePermitFee: "$50",
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "SOUTH EUCLID",
    municipalityType: "city" as const,
    population: 21000,
    buildingDeptPhone: "216-691-4200",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Every 2 years",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$75",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "STRONGSVILLE",
    municipalityType: "city" as const,
    population: 45000,
    buildingDeptPhone: "440-580-3110",
    buildingDeptWebsite: "https://www.strongsville.org/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$85",
    deckPermitRequired: true,
    deckPermitFee: "$85",
    fencePermitRequired: true,
    fencePermitFee: "$40",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "UNIVERSITY HEIGHTS",
    municipalityType: "city" as const,
    population: 13000,
    buildingDeptPhone: "216-932-7800",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021 + Local",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$150",
    pointOfSaleNotes: "Comprehensive interior and exterior",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$75/unit",
    rentalInspectionRequired: true,
    rentalInspectionFrequency: "Every 2 years",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$85",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    strPermitRequired: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "VALLEY VIEW",
    municipalityType: "village" as const,
    population: 2000,
    buildingDeptPhone: "216-524-6511",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "None",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: false,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: false,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "WALTON HILLS",
    municipalityType: "village" as const,
    population: 2300,
    buildingDeptPhone: "440-232-7800",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local",
    pointOfSaleRequired: false,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "WARRENSVILLE HEIGHTS",
    municipalityType: "city" as const,
    population: 13000,
    buildingDeptPhone: "216-587-6500",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$100",
    pointOfSaleValidDays: 120,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$60",
    deckPermitRequired: true,
    fencePermitRequired: true,
    fenceHeightLimit: "6ft",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: true,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "WESTLAKE",
    municipalityType: "city" as const,
    population: 32000,
    buildingDeptPhone: "440-617-4234",
    buildingDeptWebsite: "https://www.cityofwestlake.org/building",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "IPMC 2021",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$125",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: true,
    rentalRegistrationFee: "$50/unit",
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    roofPermitFee: "$100",
    deckPermitRequired: true,
    deckPermitFee: "$100",
    fencePermitRequired: true,
    fencePermitFee: "$50",
    fenceHeightLimit: "6ft rear, 4ft front",
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: true,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },

  {
    municipality: "WOODMERE",
    municipalityType: "village" as const,
    population: 800,
    buildingDeptPhone: "216-831-1355",
    buildingCode: "OBC 2024",
    residentialCode: "ORC 2024",
    electricalCode: "NEC 2023",
    plumbingCode: "OPC 2024",
    mechanicalCode: "OMC 2024",
    fireCode: "OFC 2024",
    propertyMaintenanceCode: "Local",
    pointOfSaleRequired: true,
    pointOfSaleFee: "$150",
    pointOfSaleValidDays: 180,
    rentalRegistrationRequired: false,
    occupancyPermitRequired: true,
    roofPermitRequired: true,
    deckPermitRequired: true,
    fencePermitRequired: true,
    hvacPermitRequired: true,
    hvacLicensedContractorRequired: true,
    electricalPermitRequired: true,
    electricalLicensedContractorRequired: true,
    plumbingPermitRequired: true,
    plumbingLicensedContractorRequired: true,
    demolitionPermitRequired: true,
    aduAllowed: false,
    strAllowed: false,
    smokeDetectorRequirements: "Per state code",
    coDetectorRequirements: "Per state code",
  },
];

// Seed all municipality code matrix data
export const seedMunicipalityCodeMatrix = mutation({
  args: {},
  handler: async (ctx) => {
    let inserted = 0;
    let updated = 0;

    for (const data of MUNICIPALITY_CODE_MATRIX) {
      // Check if already exists
      const existing = await ctx.db
        .query("municipalityCodeMatrix")
        .withIndex("by_municipality", (q) => q.eq("municipality", data.municipality))
        .first();

      if (existing) {
        await ctx.db.patch(existing._id, { ...data, lastUpdated: Date.now() });
        updated++;
      } else {
        await ctx.db.insert("municipalityCodeMatrix", { ...data, lastUpdated: Date.now() });
        inserted++;
      }
    }

    return { inserted, updated, total: MUNICIPALITY_CODE_MATRIX.length };
  },
});

// Export count for verification
export const getCount = mutation({
  args: {},
  handler: async (ctx) => {
    const all = await ctx.db.query("municipalityCodeMatrix").collect();
    return {
      total: all.length,
      cities: all.filter(m => m.municipalityType === "city").length,
      villages: all.filter(m => m.municipalityType === "village").length,
      townships: all.filter(m => m.municipalityType === "township").length,
      withPOS: all.filter(m => m.pointOfSaleRequired).length,
      withRentalReg: all.filter(m => m.rentalRegistrationRequired).length,
    };
  },
});
